//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simile
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicPlayEntities3 : DbContext
    {
        public MusicPlayEntities3()
            : base("name=MusicPlayEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GenreMaster> GenreMasters { get; set; }
        public DbSet<MusicAlbum> MusicAlbums { get; set; }
        public DbSet<MusicArtist> MusicArtists { get; set; }
        public DbSet<MusicBand> MusicBands { get; set; }
        public DbSet<MusicTag> MusicTags { get; set; }
    }
}
