//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simile
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicTag
    {
        public int Id { get; set; }
        public System.TimeSpan Length { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public decimal FileSize { get; set; }
        public bool IsDeleted { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
        public Nullable<int> BandId { get; set; }
        public string Path { get; set; }
    }
}
